function obj = bcg(varargin)

import physioset.event.*;
import spt.criterion.terp.terp;

obj = terp(...
    'EventSelector',    class_selector('Class', 'qrs'), ...
    'LatencyRange',     [-0.2 0.9], ...
    'MaxCard',          10, ...
    'MinCard',          3, ...
    'Percentile',       70, ...
    'MaxShift',         .1, ...
    'Filter',           @(sr) filter.hpfilt('fp', 2/(sr/2)), ...
    varargin{:});


end