function fileName = get_output_filename(obj, data)
% GET_OUTPUT_FILENAME - Name of the data file generated by a node
%
% fileName = get_output_filename(obj, data);
%
% Where
%
% DATA is the input to the node.
%
% FILENAME is the full path name of the data file generated by the node.
% Note that such datafile may exist only if the Save property of the node
% is set to true.
%
% See also: meegpipe.node



import goo.pkgisa;
import meegpipe.node.globals;
import mperl.file.spec.catfile;
import exceptions.*;
import misc.var2name;
import pset.session;
import mperl.cwd.abs_path;

savePath =  globals.get.SavePath;
origFile = globals.get.OrigFile;

if pkgisa(data, 'physioset.physioset') || ischar(data),
    
    if isempty(origFile),
        if ischar(data),
            origFile = data;
        else
            origFile = get_datafile(data);
        end
    end
    
    [~, name, ext] = fileparts(origFile);
    
    if isempty(savePath)
        savePath = get_full_dir(obj, data);
    end
    
    objName = get_name(obj);    
    if isempty(objName),
        objName = regexprep(class(obj), '.+?\.([^\.]+)$', '$1');        
    end
    objName = strrep(objName, '_', '-');
    
    fileName = catfile(savePath, [name '_' objName ext]);
    
else
    
    if isempty(savePath),
        savePath = get_full_dir(obj, data);
    end
    
    objName = get_name(obj);    
    if isempty(objName),
        objName = regexprep(class(obj), '.+?\.([^\.]+)$', '$1');        
    end
    objName = strrep(objName, '_', '-');
   
    fileName = catfile(savePath, ...
        [var2name(data) '_' objName globals.get.HdrFileExt]);
    
end




end