function [pName, pVal, pDescr] = report_info(obj)

pName  = { ...
    'Name', ...
    'OGE', ...
    'Save', ...
    'Config', ...
    'DataSelector', ...
    'GenerateReport', ...
    };

pDescr = {...
    'Name of the node', ...
    'Should Oracle Grid Engine be used, if available?', ...
    'Save node output data to a disk file', ...
    'Node configuration options', ...
    'Selects the data to be processed by the node', ...
    'Should a data processing report be generated?' ...
    };


pVal = cell(size(pName));

for i = 1:numel(pName)
   pVal{i} = obj.(pName{i}); 
end

% Add also configuration information
[pNameCfg, pValCfg, pDescrCfg] = report_info(get_config(obj));

pName  = [pName(:); pNameCfg(:)];
pVal   = [pVal(:); pValCfg(:)];
pDescr = [pDescr(:); pDescrCfg(:)];


end