function myNode = bss_supervised(varargin)
% BSS_SUPERVISED - Fully supervised BSS-based artifact rejection


myPCA = spt.pca(...
    'RetainedVar',  99.999, ...
    'MinCard',      @(lambda) min(40, max(2, 0.15*numel(lambda))), ...
    'MaxCard',      45);
myNode = meegpipe.node.bss.new(...
    'PCA',  myPCA, ...
    'Name', 'bss-supervised', ...
    varargin{:});
 


end