function myNode = bss_supervised(varargin)
% BSS_SUPERVISED - Fully supervised BSS-based artifact rejection



mySel = pset.selector.cascade(...
    pset.selector.sensor_class('Class', 'EEG'), pset.selector.good_data);
myPCA = spt.pca(...
    'RetainedVar',  99.975, ...
    'MinCard',      @(lambda) min(25, max(2, 0.15*numel(lambda))), ...
    'MaxCard',      40);

myFeat = spt.feature.bp_var;

myCrit = spt.criterion.threshold(...
    'MaxCard', 0, ...  % Do not reject anything automatically
    'Feature', myFeat ...
    );
myNode = meegpipe.node.bss.new(...
    'Criterion',    myCrit, ...
    'DataSelector', mySel, ...
    'PCA',          myPCA, ...
    'Name',         'bss-supervised', ...
    varargin{:});
 


end