function myNode = bss_supervised(varargin)
% BSS_SUPERVISED - Fully supervised BSS-based artifact rejection



mySel = pset.selector.cascade(...
    pset.selector.sensor_class('Class', 'EEG'), pset.selector.good_data);
myPCA = spt.pca(...
    'RetainedVar',  99.999, ...
    'MinCard',      @(lambda) min(30, max(2, 0.15*numel(lambda))), ...
    'MaxCard',      40);
myNode = meegpipe.node.bss.new(...
    'DataSelector', mySel, ...
    'PCA',  myPCA, ...
    'Name', 'bss-supervised', ...
    varargin{:});
 


end