function obj = bcg(varargin)

import spt.criterion.acf.acf;


obj = acf(...
    'MADs',         0, ...   
    'Period',       1.2, ...
    'PeriodMargin', 0.5, ...
    'Min',          0.1, ...
    'MaxCard',      5, ...
    'Percentile',   50, ...
    'Filter',       @(sr) filter.lpfilt('fc', 20/(sr/2)), ...
    varargin{:});


end