function [pName, pValue, pDescr]   = report_info(obj)
% REPORT_INFO - Information regarding construction parameters
%
% 
% See also: report.reportable


pName = {...
    'AR', ...   
    'VAR' ...
    };
    
pDescr = {...
    'Use individual 1-D AR models?', ...   
    'VAR model estimation algorithm' ...
    };

pValue = cellfun(@(x) obj.(x), pName, 'UniformOutput', false);
