function critObj = emg(varargin)


critObj   =  spt.criterion.psd_ratio.new(...
    'Band1',        [40 100], ...
    'Band2',        [2 30], ...
    'MaxCard',      5, ...
    'MinCard',      1, ...
    'Max',          @(r) max(1, median(r) + 10*mad(r,1)));

end