function obj = pwl(varargin)


import spt.criterion.psd_ratio.psd_ratio;

obj = psd_ratio( ...
    'Band1',        [49 51], ...
    'Band2',        [3 11], ...
    'Max',          30, ...
    'MinCard',      0, ...
    'MaxCard',      2, ...
    varargin{:}     ...
    );


end