function obj = theta(varargin)

import spt.criterion.psd_ratio.psd_ratio;

obj = psd_ratio( ...
    'Band1',        [4 8], ...
    'Band2',        [8 10], ...
    'MinCard',      1, ...  % by default just one theta component
    'MaxCard',      1, ...
    'Estimator',    @(x, sr) pwelch(x, [], [], [], sr), varargin{:} ...
    );


end