function [pName, pValue, pDescr]   = report_info(obj)
% REPORT_INFO - Information regarding construction parameters
%
% 
% See also: report.reportable

% Documentation: class_filter_lpfilt.txt
% Description: Information regarding construction arguments

pName = {...
    'Specs', ...
    'Order', ...
    'Delay', ...
    'DesignMethod', ...
    'PersistentMemory' ...
    };
    
pDescr = {...
    'Filter specifications', ...
    'Filter order', ...
    'Filter delay', ...
    'Design method', ...
    'Is the filter memory persistent?' ...
    };

pValue = cellfun(@(x) obj.(x), pName, 'UniformOutput', false);
