function obj = pwl(varargin)

import spt.criterion.thilbert.*;

myFilter = @(sr) filter.bpfilt('fp',  [45 55]/(sr/2));

obj = thilbert(...
    'Max'           , 1/0.1, ...
    'MinCard'       , 0, ...
    'MaxCard'       , 2, ...   
    'MADs'          , [Inf 5], ...
    'Filter'        , myFilter, ...
    varargin{:});


end