function crit = eog(varargin)


crit = spt.criterion.var.new( ...
    'Filter',   @(sr) filter.lpfilt('fc', 7/(sr/2)), ...
    'MaxCard',  5, ...
    'MinCard',  2, ...
    'Max',      @(r) median(r) + 4*mad(r), ...
    varargin{:});


end