function myNode = abp(varargin)
% ABP - Extraction of Arterial Blood Pressure features

import meegpipe.node.*;

featNames = {...
    'systolic_bp',  ...
    'diastolic_bp', ...
    'pulse_pressure',  ...
    'mean_pressure', ...
    'mean_dyneg', ...
    'area_under_systole1', ...
    'area_under_systole2',  ...
    'heart_rate', ...
    'co' ...
    };

featList = {...
    @(data, ev, sel) features.abp.systolic_bp(data, data.SamplingRate); ...
    @(data, ev, sel) features.abp.diastolic_bp(data, data.SamplingRate); ...
    @(data, ev, sel) features.abp.pulse_pressure(data, data.SamplingRate); ...
    @(data, ev, sel) features.abp.mean_pressure(data, data.SamplingRate); ...
    @(data, ev, sel) features.abp.mean_dyneg(data, data.SamplingRate); ...
    @(data, ev, sel) features.abp.area_under_systole1(data, data.SamplingRate); ...
    @(data, ev, sel) features.abp.area_under_systole2(data, data.SamplingRate); ...
    @(data, ev, sel) features.abp.heart_rate(data, data.SamplingRate); ...
    @(data, ev, sel) features.abp.co(data, data.SamplingRate) ...
    };


myNode = generic_features.new(...
    'Name',         'abp-features', ...
    'FirstLevel',   featList, ...
    'FeatureNames', featNames, ...
    'DataSelector', pset.selector.sensor_label('^BP'), ...
    varargin{:} ...
    );

end