function myNode = bss_regr(varargin)
% BSS - BCG correction using Blind Source Separation and regression

import meegpipe.node.*;

mySel1 = pset.selector.sensor_class('Class', 'EEG');
mySel2 = pset.selector.good_data;
mySel  = pset.selector.cascade(mySel1, mySel2);

myPCA = spt.pca('MaxCard', @(lambda) ceil(floor(0.4*numel(lambda))));
tpcaFilter = filter.tpca('Order', @(sr) min(50, ceil(sr/10)), 'PCA', myPCA);
tpcaFilter = filter.sliding_window(tpcaFilter, ...
    'WindowLength', @(sr) 30*sr, ...
    'WindowOverlap', 50);

myRegrFilter = filter.mlag_regr('Order', 10);
myRegrFilter = filter.sliding_window(...
    'Filter',        myRegrFilter, ...
    'WindowLength',  @(sr) sr*10, ...
    'WindowOverlap', 50);

myFeat1 = spt.feature.qrs_erp(...
    'Duration',  0.7, ...
    'Offset',    0.02 ...
    );

myFeat2 = spt.feature.psd_ratio(...
    'TargetBand',   [1 6], ...
    'RefBand',      [7 12]);

myCrit = spt.criterion.threshold(myFeat1, myFeat2, ...
    'Max',      {0.5, 2}, ...
    'MinCard',  4);

myPCA = spt.pca(...
    'LearningFilter',   @(sr) filter.lpfilt('fc', 20/(sr/2)), ...
    'RetainedVar',      99.5, ...
    'MaxCard',          40, ...
    'MinCard',          @(lambda) max(3, ceil(0.05*numel(lambda))) ...
    );

myNode = bss.new(...
    'DataSelector', mySel, ...
    'BSS',          spt.bss.multicombi, ...
    'PCA',          myPCA, ...
    'Filter',       tpcaFilter, ...
    'RegrFilter',   myRegrFilter, ...
    'Criterion',    myCrit, ...
    varargin{:});
    

end