function myNode = sensor_noise(varargin)
% SENSOR_NOISE - Sparse sensor noise

import misc.process_arguments;
import misc.split_arguments;
import pset.selector.sensor_class;
import pset.selector.good_data;
import pset.selector.cascade;

%% Default criterion
myFeat1 = spt.feature.sgini;
myCrit = spt.criterion.threshold('Feature', myFeat1, ...
    'MinCard',  1, ...
    'Max',      @(x) median(x) + 2*mad(x), ...
    'MaxCard',  4);

%% Process input arguments
opt.RetainedVar     = 99.99;
opt.MaxPCs          = 40;
opt.MinPCs          = @(lambda) max(3, ceil(0.1*numel(lambda)));
opt.BSS             = spt.bss.efica;
opt.Criterion       = myCrit; 

[thisArgs, varargin] = split_arguments(fieldnames(opt), varargin);

[~, opt] = process_arguments(opt, thisArgs);

%% PCA
myPCA = spt.pca(...
    'RetainedVar',              opt.RetainedVar, ...
    'MaxCard',                  opt.MaxPCs, ...
    'MinCard',                  opt.MinPCs, ...
    'MinSamplesPerParamRatio',  15);

%% Build the bss node
dataSel = cascade(sensor_class('Class', {'EEG', 'MEG'}), good_data);
myNode = meegpipe.node.bss.new(...
    'DataSelector', dataSel, ...
    'Criterion',    opt.Criterion, ...
    'PCA',          myPCA, ...
    'BSS',          opt.BSS, ...
    'Filter',       [], ...
    'RegrFilter',   [], ...
    'Name',         'bss.eog', ...
    varargin{:});


end